apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
        - name: alert-service
          image: <your-docker-repo>/alert-service:latest
          ports:
            - containerPort: 3003
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5
