image:
  repository: docker.io/blackkolly/consumer-service
  tag: 1.0.2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3002
env:
  KAFKA_BROKER: kafka-release-kafka:9092
  TOPIC: crypto-stream
  MONGODB_URI: mongodb://mongodb-release-mongodb:27017/streamdb
  periodSeconds: 5
prometheus:
  enabled: true
