image:
  repository: docker.io/blackkolly/data-stream-backend
  tag: 1.0.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 4000
env:
  MONGODB_URI: mongodb://mongodb-release-mongodb:27017/streamdb
  PRODUCER_URL: http://producer:3001/produce
prometheus:
  enabled: true
