replicaCount: 1
image:
  repository: <your-docker-repo>/kafka-microservices
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
kafka:
  enabled: true
  image: bitnami/kafka:latest
  replicaCount: 1
mongodb:
  enabled: true
  image: bitnami/mongodb:latest
  replicaCount: 1
