replicaCount: 1
image:
  repository: bitnami/mongodb
  tag: latest
  pullPolicy: IfNotPresent
env:
  MONGODB_ROOT_PASSWORD: strongpassword
  MONGODB_DATABASE: streamdb
service:
  type: ClusterIP
  port: 27017
