image:
  repository: docker.io/blackkolly/producer-service
  tag: 1.0.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3001
env:
  KAFKA_BROKER: kafka-release-kafka:9092
  TOPIC: crypto-stream
prometheus:
  enabled: true
