image:
  repository: bitnami/kafka
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9092
env:
  KAFKA_CFG_PROCESS_ROLES: "broker"
  KAFKA_CFG_NODE_ID: "1"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
