apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: netflix-app
    tier: config
    managed-by: kubectl
    environment: production
    # Add more labels as needed
data:
  REACT_APP_API_URL: "https://yourdomain.com/api"
  # Backend config values
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
  FEATURE_X_ENABLED: "true"
  # Add more backend config values as needed
