apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app.kubernetes.io/name: consumer
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/component: consumer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.1.0
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app.kubernetes.io/name: consumer
    app.kubernetes.io/instance: myapp
