apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/component: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.1.0
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: myapp
