apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app.kubernetes.io/name: producer
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/component: producer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.1.0
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app.kubernetes.io/name: producer
    app.kubernetes.io/instance: myapp
