services:
  alert:
    enabled: true
    image: blackkolly/alert-service:1.0.0
    port: 3003
    env:
      ALERT_EMAIL: alerts@example.com
  backend:
    enabled: true
    image: blackkolly/data-stream-backend:1.0.0
    port: 4000
    env:
      MONGODB_URI: mongodb://umbrella-release-mongodb:27017/streamdb
  consumer:
    enabled: true
    image: blackkolly/consumer-service:1.0.0
    port: 3002
    env:
      KAFKA_BROKER: umbrella-release-kafka:9092
      TOPIC: crypto-stream
      MONGODB_URI: mongodb://umbrella-release-mongodb:27017/streamdb
  frontend:
    enabled: true
    image: blackkolly/frontend:1.0.0
    port: 80
  kafka:
    enabled: true
    image: bitnami/kafka:latest
    port: 9092
    env:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_BROKER_ID: "1"

  zookeeper:
    enabled: true
    image: bitnami/zookeeper:latest
    port: 2181
  mongodb:
    enabled: true
    image: bitnami/mongodb:latest
    port: 27017
    env:
      MONGODB_DATABASE: streamdb
      MONGODB_ROOT_PASSWORD: strongpassword
  producer:
    enabled: true
    image: blackkolly/producer-service:1.0.0
    port: 3001
    env:
      KAFKA_BROKER: umbrella-release-kafka:9092
      TOPIC: crypto-stream
      MONGODB_URI: mongodb://umbrella-release-mongodb:27017/streamdb
