apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-db-pv
  labels:
    app: flask-ecommerce
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/flask-ecommerce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-db-pvc
  namespace: flask-ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
