apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secrets
  namespace: flask-ecommerce
type: Opaque
data:
  # Base64 encoded secret key - replace with your actual secret
  SECRET_KEY: Y2hhbmdlX21lX3RvX2FfcmFuZG9tX3NlY3JldF9rZXk=
  # Base64 encoded database password if using external DB
  DB_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: flask-ecommerce
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded Docker registry credentials
  # Use: kubectl create secret docker-registry registry-secret --docker-server=your-registry --docker-username=user --docker-password=pass --docker-email=email
  .dockerconfigjson: ""
