version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  producer-service:
    build: ./Nodejs_App/producer-service
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "3001:3001"
    depends_on:
      - kafka
  consumer-service:
    build: ./Nodejs_App/consumer-service
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=events
    ports:
      - "3002:3002"
    depends_on:
      - kafka
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  data-stream-backend:
    build: ./Nodejs_App
    environment:
      - PRODUCER_URL=http://producer-service:3001/produce
      - CONSUMER_SERVICE_URL=http://consumer-service:3002/api/consumed
    ports:
      - "4000:4000"
    depends_on:
      - producer-service
      - consumer-service
      - kafka
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
volumes:
  mongo_data:
