apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: test-namespace
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka-microservices
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka-microservices
